#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="librewolf"
export QT_QPA_PLATFORMTHEME="qt6ct"

export DOTNET_CLI_TELEMETRY_OPTOUT=1

export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"

setxkbmap -option caps:swapescape
#[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx
