#!/bin/sh

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all

Alt=Mod1
Super=Mod4

Term=alacritty

hc keybind $Alt-Return spawn $Term
hc keybind $Alt-d spawn rofi -show drun

hc keybind $Alt-q close
hc keybind $Alt-r remove
hc keybind $Alt-Shift-r reload
hc keybind $Alt-e spawn ~/.local/bin/hl-quit.sh

hc keybind $Alt-h focus left
hc keybind $Alt-j focus down
hc keybind $Alt-k focus up
hc keybind $Alt-l focus right

hc keybind $Alt-Shift-h     shift left
hc keybind $Alt-Shift-j     shift down
hc keybind $Alt-Shift-k     shift up
hc keybind $Alt-Shift-l     shift right

hc keybind $Super-h split left 0.5
hc keybind $Super-j split bottom 0.5
hc keybind $Super-k split top 0.5
hc keybind $Super-l split right 0.5
hc keybind $Super-space split explode

resizestep=0.01
hc keybind $Alt-Control-h       resize left +$resizestep
hc keybind $Alt-Control-j       resize down +$resizestep
hc keybind $Alt-Control-k       resize up +$resizestep
hc keybind $Alt-Control-l       resize right +$resizestep

hc keybind $Alt-f floating toggle
hc keybind $Alt-Shift-f fullscreen toggle

hc keybind $Super-a spawn ~/.local/bin/generic/togglekbl.sh

hc keybind XF86AudioLowerVolume spawn pamixer -d 3
hc keybind XF86AudioRaiseVolume spawn pamixer -i 3

hc keybind XF86MonBrightnessDown spawn xbacklight -dec 3
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 3

hc rename default 1 || true
hc keybind "$Alt-1" use_index 0
hc keybind "$Alt-Shift-1" move_index 0
index=1
for tag in 2 3 4 7 8 9 0; do
	hc add "$tag"
	hc keybind "$Alt-$tag" use_index "$index"
	hc keybind "$Alt-Shift-$tag" move_index "$index"
	index="$(( index + 1 ))"
done

hc mouseunbind --all
hc mousebind $Alt-Button1 move
hc mousebind $Alt-Button2 zoom
hc mousebind $Alt-Button3 resize

hc unrule -F

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#88713ecc'
hc set frame_border_normal_color '#212121cc'
hc set frame_bg_normal_color '#565656d0'
hc set frame_bg_active_color '#fefefef0'
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 4

#hc attr theme.title_font 'monospace:pixelsize=12'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
#hc attr theme.title_depth 3  # space below the title's baseline
#hc attr theme.title_color '#ffffff'
#hc attr theme.normal.title_color '#898989'
#hc attr theme.title_height 15
#hc attr theme.tab_color '#1f1f1fdd'
#hc attr theme.active.tab_color '#2b4F0add'
#hc attr theme.active.tab_outer_color '#6c8257dd'
#hc attr theme.active.tab_title_color '#ababab'
#hc attr theme.floating.outer_color black
#for state in active urgent normal ; do
#    hc substitute C theme.${state}.inner_color \
#        attr theme.${state}.outer_color C
#done
hc attr theme.title_when never
hc attr theme.active.color '#345f0cef'
hc attr theme.normal.color '#323232dd'
hc attr theme.urgent.color '#7811a1dd'
hc attr theme.inner_color black
hc attr theme.inner_width 2
hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#141414'
hc attr theme.active.inner_color '#a8915e'
hc attr theme.urgent.inner_color '#9d6570'
hc attr theme.normal.inner_color '#606060'

hc set window_gap 8
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

hc set tree_style '╾│ ├└╼─┐'

hc unlock

panel=~/.config/herbstluftwm/panel.sh
"$panel" &
