#!/bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
killall -q polybar
while pgrep -u $UID -x polybar > /dev/null; do
	sleep 1;
done
polybar --config=~/.config/polybar/config.ini top &
if [ -n "$( xrandr -q | grep 'DP2 connected' )" ]; then
	xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output DP2 --mode 1440x900 --rotate normal --right-of eDP1
#	polybar --config=~/.config/polybar/config.ini external &
fi

# monitor
bspc monitor eDP1 -d 1 2 3 4
bspc monitor DP2 -d A B C

# appearance
bspc config border_width 	2
bspc config window_gap 		8
bspc config split_ratio		0.5
bspc config borderless_monocle 	true
bspc config gapless_monocle 	true

bspc config -m DP2 top_padding 0

exit 0
