[colors]
#background = "#1a1c1e"
draw_bold_text_with_bright_colors = true
#foreground = "#c5c8c6"

#[cursor]
#blinking = false

[font]
size = 12.0

[font.bold]
family = "Mononoki Nerd Font"
style = "Light"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Light Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Extra Light Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "ExtraLight"

[window]
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8
